### ISSUE TITLE
undefined local variable or method `config' in /usr/src/app/bin/duplication

### ISSUE THREAD

**Issue by winniehell** [codeclimate/codeclimate-duplication#212]
When using the `codeclimate/codeclimate` Docker image, we started getting

```
/usr/src/app/bin/duplication:16:in `<main>': undefined local variable or method `config' for main:Object (NameError)
```

about three hours ago (`2017-08-30T17:56Z` was the [first failure]).

A downgrade of the `codeclimate/codeclimate` Docker image didn't help: https://gitlab.com/gitlab-org/gitlab-ce/-/jobs/30809782

I'm assuming that this is caused by https://github.com/codeclimate/codeclimate-duplication/commit/a55e6160aad8c5a672a854e68f3997cdce3338dc#commitcomment-23983826.

[first failure]: https://gitlab.com/gitlab-org/gitlab-ce/-/jobs/30798751

**Comment by winniehell** [comment]
@dblandin Thank you for the blazingly fast fix! :rocket: I can confirm our builds are passing now.

> Any reason why you're using the CLI directly in CI instead of Code Climate's GitLab support

I don't know who made that decision, so I can only guess: This way we only rely on our own infrastructure and not on an external service. This way we are also able to dogfood our own [Code Quality integration feature](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality_diff.html). :smiley:

**Comment by dblandin** [comment]
> we are also able to dogfood our own Code Quality integration feature. 😃

Ahh, very cool! Haven't seen that yet. :ok_hand:
